# Generated by Django 3.1.7 on 2021-04-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='producto_referencia',
        ),
        migrations.AddField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='appEntrega.producto'),
        ),
        migrations.AddField(
            model_name='componente',
            name='producto_padre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='producto_padre', to='appEntrega.producto'),
        ),
    ]
