# Generated by Django 3.2 on 2021-04-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrega', '0003_auto_20210425_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='componente_producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='componente_producto', to='appEntrega.producto'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='componente_producto_padre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='componente_producto_padre', to='appEntrega.producto'),
        ),
    ]
