# Generated by Django 3.2 on 2021-04-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrega', '0004_auto_20210425_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('linea_referencia', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('linea_descripcion', models.CharField(max_length=250)),
                ('linea_unidades', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('linea_precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('linea_linea_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEntrega.factura')),
            ],
        ),
        migrations.RemoveField(
            model_name='orden_pedido',
            name='pedido_precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='componente',
            name='componente_producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='appEntrega.producto'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='componente_producto_padre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='producto_padre', to='appEntrega.producto'),
        ),
        migrations.DeleteModel(
            name='Orden_Linea',
        ),
        migrations.AddField(
            model_name='factura',
            name='linea_pedido_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEntrega.orden_pedido'),
        ),
        migrations.AddField(
            model_name='factura',
            name='linea_producto_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEntrega.producto'),
        ),
    ]
